name: log aggregator 

on:
  push:
    branches:
      - main
    paths:
      - 'log-aggregator/**'
      - '.github/workflows/aggregator-ci.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'log-aggregator/**'
      - '.github/workflows/aggregator-ci.yml'
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: build docker
        uses: docker/setup-buildx-action@v2

      - name: run docker
        working-directory: ./log-aggregator
        run: docker compose up --build -d

      - name: wait for it
        run: sleep 15

      - name: check contaainer
        run: docker ps -a

      - name: cleanup
        working-directory: ./log-aggregator
        run: docker compose down
