name: CI for multiapp demo
on:
  push:
    branches: [ main ]
    paths:
      - 'multi-app-demo/**'
      - '.github/workflows/multi-app-demo.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'multi-app-demo/**'
      - '.github/workflows/multi-app-demo.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: multi-app-demo

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build docker image
        run: docker compose -f multi-app-demo/docker-compose.yml build

      - name: run docker image
        run: docker compose -f multi-app-demo/docker-compose.yml up -d

      - name: check running containers
        run: docker compose -f multi-app-demo/docker-compose.yml ps

      - name: test app1 endpoints
        run: |
          echo "testing app1 endpoints..."
          sleep 5
          curl -f http://localhost:5001/number
          echo "testing app2 endpoints..."
          sleep 10
          curl -f http://localhost:5002/result

      - name: stop containers
        if: always()
        run: docker compose -f multi-app-demo/docker-compose.yml down

